on:
  push:
  pull_request:
    branches:
      - "main"

name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@main
      - run: cargo test --verbose

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@main
      - run: cargo clippy --verbose

  fmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - uses: actions/checkout@main
      - run: cargo fmt --all --check
